### ISSUE TITLE
[ACCUEIL] Center le mandala

### ISSUE THREAD

**Issue by Yassine2b** [Epsilon-partners/GOA-app#17]

**Comment by ClarisseRodrigues** [comment]
Le mandala doit prendre toute la hauteur

**Comment by ImadEM21** [comment]
@ClarisseRodrigues @Axelle2021 
Dans l'image en question le mandala ne prend pas toute la hauteur du coup avec cette image il y aura toujours de l'espace vert en haut et en bas
![Banner](https://user-images.githubusercontent.com/70642895/110037763-23aec500-7d3f-11eb-9127-79435cd3c467.png)
