### ISSUE TITLE
[VOS COORDONNES] Si 2 personnes commande en tant qu'invité avec le même nom, les commandes se mélanges et les 2 pourront voir les commandes de l'autres

### ISSUE THREAD

**Issue by Yassine2b** [Epsilon-partners/GOA-app#21]
Dans le cas d'un invité, il faudrait un id interne pour distinguer les personnes. Voir utiliser le cache PC pour stocker la valeur de l'ID.

**Comment by Axelle2021** [comment]
Une fois les coordonnées valider, une fenêtre pop-up s'affiche en signalant que la commande a bien été prise en compte. Lorsqu'on clique sur la bouton pour revenir à l'accueil et qu'on retourne sur notre panier, il apparaît vide. La commande a-t-elle été bien prise en compte malgré tout ? Je pense qu'il faudrait afficher un message d'erreur dans ce cas...?
