### ISSUE TITLE
[CREER UN COMPTE] Pas de message d'erreur quand les mots de passe sont différents

### ISSUE THREAD

**Issue by Yassine2b** [Epsilon-partners/GOA-app#31]

**Comment by Axelle2021** [comment]
Le message d'erreur apparaît bien mais il y a une faute d'orthographe, il faut écrire : "Les mots de passe ne sont pas égaux !". De plus, il faudrait qu'une croix apparaisse dans le champ de texte plutôt qu'un symbole "ok" alors qu'il y a une erreur.
